name: whitevault
description: "A private creative playground app."
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # firebase_core: ^4.0.0  # Temporarily disabled for App Store build
  # firebase_auth: ^6.0.0  # Temporarily disabled for App Store build
  # cloud_firestore: ^4.17.5  # Temporarily commented out due to gRPC -G flag issue
  # firebase_storage: ^11.7.7  # Temporarily commented out due to Xcode 16.4 compatibility
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  pdf: ^3.11.3
  # New advanced feature dependencies
  http: ^1.1.0
  image: ^4.1.3
  vector_math: ^2.1.4
  audioplayers: ^6.5.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
